<a href="https://colab.research.google.com/github/VaibhavNagrale007/Adversarial-Machine-Learning-BTP/blob/main/Sem%207/red_attack_GTSRB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Model creation

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Specify the path to your dataset
dataset_path = '/content/drive/MyDrive/Dataset/GTSRB-Dataset'

# Set up data generators
datagen = ImageDataGenerator(rescale=1./255)

# Specify the target size based on your model's input shape
target_size = (30, 30)

batch_size = 32

train_generator = datagen.flow_from_directory(
    directory=dataset_path + '/Train',
    target_size=target_size,
    batch_size=batch_size,
    class_mode='categorical',  # Use 'categorical' for multiclass classification
    shuffle=True
)

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.models import save_model, load_model

# Adjust the output layer to have the number of classes in your dataset
num_classes = 44  # Update this based on your dataset
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(30, 30, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')  # Multiclass classification
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Assuming your training steps per epoch is the number of training samples divided by the batch size
steps_per_epoch = len(train_generator) // batch_size

# Train the model
model.fit(train_generator, epochs=15, steps_per_epoch=steps_per_epoch)

# Save the model
model.save('/content/drive/MyDrive/Dataset/pmodel-GTSRB.h5')

Found 34005 images belonging to 44 classes.
Epoch 1/15
33/33 [==============================] - 356s 11s/step - loss: 3.5560 - accuracy: 0.0833
Epoch 2/15
33/33 [==============================] - 341s 10s/step - loss: 3.1898 - accuracy: 0.1591
Epoch 3/15
33/33 [==============================] - 332s 10s/step - loss: 2.9102 - accuracy: 0.2491
Epoch 4/15
33/33 [==============================] - 320s 10s/step - loss: 2.4644 - accuracy: 0.3996
Epoch 5/15
33/33 [==============================] - 297s 9s/step - loss: 2.0425 - accuracy: 0.4498
Epoch 6/15
33/33 [==============================] - 294s 9s/step - loss: 1.7995 - accuracy: 0.4943
Epoch 7/15
33/33 [==============================] - 285s 9s/step - loss: 1.5278 - accuracy: 0.5691
Epoch 8/15
33/33 [==============================] - 282s 9s/step - loss: 1.2650 - accuracy: 0.6581
Epoch 9/15
33/33 [==============================] - 264s 8s/step - loss: 1.1446 - accuracy: 0.6884
Epoch 10/15
33/33 [==============================] - 269s 8s/

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


Code

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2
from PIL import Image
import os

In [ ]:
# Reading the input images and putting them into a numpy array
data=[]
labels=[]

height = 30
width = 30
channels = 3
classes = 43
n_inputs = height * width * channels

for i in range(classes):
    path = "/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/".format(i)
    print(path)
    Class = os.listdir(path)
    for a in Class:
        try:
            image = cv2.imread(path+a)
            image_from_array = Image.fromarray(image, 'RGB')
            size_image = image_from_array.resize((height, width))
            data.append(np.array(size_image))
            labels.append(i)
        except AttributeError:
            print(" ")

Cells = np.array(data)
labels = np.array(labels)

# Randomize the order of the input images
s = np.arange(Cells.shape[0])
np.random.seed(43)
np.random.shuffle(s)
Cells = Cells[s]
labels = labels[s]

from tensorflow.keras.models import load_model
model = load_model("/content/drive/MyDrive/Dataset/pmodel-GTSRB.h5")
print(path)

# Predicting with the test data
y_test = pd.read_csv("/content/drive/MyDrive/Dataset/GTSRB-Dataset/Test.csv").head(1000)
labels = y_test['Path'].to_numpy()
y_test = y_test['ClassId'].values

data = []


/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Dataset/GTSRB-Dataset/Train/0/
/content/drive/MyDrive/Datas

In [ ]:
print(data)
print(labels)

In [ ]:
# a = 1
for f in labels:
    # print(a)
    # a = a+1
    image = cv2.imread("/content/drive/MyDrive/Dataset/GTSRB-Dataset/Test/" + f.replace('Test/', ''))
    image_from_array = Image.fromarray(image, 'RGB')
    size_image = image_from_array.resize((height, width))
    data.append(np.array(size_image))

In [ ]:
print(len(y_test))

1000


In [ ]:
X_test = np.array(data)

X_test = X_test.astype('float32') / 255
# pred = model.predict_classes(X_test)

predict_x = model.predict(X_test)
pred = np.argmax(predict_x, axis=1)
# print(pred)

# Accuracy with the test data
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

32/32 [==============================] - 1s 23ms/step


0.051

In [ ]:
def max_diff(img1,img2):
    img = img1 - img2
    return np.amax(img)

# returns predicted class of image
def pred(image):
    data = []
    data.append(image)
    X_test = np.array(data)
    X_test = X_test.astype('float32')/255
    X_test = X_test.reshape(1,height,width,3)
    #print(X_test.shape)
    predict_x=model.predict(X_test)
    pred_target_image=np.argmax(predict_x,axis=1)
    #pred_target_image=pred_target_image[0]

    #pred = model.predict_classes(X_test)
    return pred_target_image[0]

def boundary_estimation(source, target, dmin):
    Ii = ((source + target)/2.0)
    k = pred(Ii)
    delta = max_diff(source, Ii)
    Ia2 = source
    Ib2 = target
    p = Ib2
    while (delta > dmin):
        if (pred(Ia2) != k):
            Ib2 = Ii
        else:
            Ia2 = Ii
        Ii = ((Ia2+Ib2)/2.0)
        k = pred(Ii)
        delta = max_diff(Ia2,Ii)
    return Ii

def go_out(source,iout,alpha):
    i_diff = iout - source
    pred_source = pred(source)
    inew = iout
    # Note: added limit to end
    limit = 10
    while (pred(inew)==pred_source):
        inew = inew + alpha*(i_diff)
        limit = limit - 1
        if (limit < 0): break

    return inew

In [ ]:
source_image_path = "/content/drive/MyDrive/Dataset/GTSRB-Dataset/Test/00032.png";
target_image_path = "/content/drive/MyDrive/Dataset/GTSRB-Dataset/Test/00042.png";
# print("SOURCE IMAGE:\n")
# print(source_image)

img = (np.asarray(Image.open(source_image_path)))
image_from_array = Image.fromarray(img, 'RGB')
img1 = image_from_array.resize((height, width))
img1=np.array(img1)
img1=img1.reshape(height,width,3)
source_image = np.array(img1)

img = (np.asarray(Image.open(target_image_path)))
image_from_array = Image.fromarray(img, 'RGB')
img2 = image_from_array.resize((height, width))
img2=np.array(img2)
img2=img2.reshape(height,width,3)
target_image = np.array(img2)

i = boundary_estimation(source_image,target_image,1.0)

1/1 [==============================] - 0s 24ms/step


In [ ]:
print (pred(i))
print (pred(source_image)) #Class of source image
print (pred(target_image)) #Class of target image

1/1 [==============================] - 0s 26ms/step
28
1/1 [==============================] - 0s 24ms/step
28
1/1 [==============================] - 0s 27ms/step
10


In [ ]:
ii = go_out(source_image,i,0.01)

1/1 [==============================] - 0s 27ms/step


In [ ]:
pred(ii)

Image.fromarray(i.astype('uint8')).show()

Image.fromarray(ii.astype('uint8')).show()

def array_diff(d1):
    sumd1 = 0.0
    for i in range(0,3):
        for j in range(0,height):
            for k in range(0,width):
                d1[j][k][i] = d1[j][k][i]*d1[j][k][i]
                sumd1 = sumd1 + d1[j][k][i]
    return (sumd1)

def gradient_estimation(source, target, adversarial, n, theta):
    Ia = source
    Ib = target
    Ii = adversarial
    Io = np.zeros((2700))
    X = np.random.randint(0,2700, size=n)
    for i in X:
        Io[i] = 255
    Io = Io.reshape((height,width,3))
#     print(Io*theta)
    Ii2 = Ii + theta*Io
    Ii2_new = boundary_estimation(Ia, Ii2, 1.0)
    Ii2_new = go_out(source,Ii2_new,0.01)
    diff2 = Ii2_new - Ia
    diff1 = Ii - Ia
    d2 = array_diff(diff2)
    d1 = array_diff(diff1)
    if (d2 > d1):
        return (-1, Ii2_new)
    elif (d1 > d2):
        return (1, Ii2_new)
    else:
        return (0,Ii2_new)

def efficient_update(source, target, adversarial, I2, g, j):
    Ia = source
    Ib = target
    Ii = adversarial
    Ii2 = I2
    delta = g*(Ii2 - Ii)
    l = j
    Inew = Ii + l*delta

    diff1 = Inew - Ia
    diff2 = Ii - Ia
    d1 = array_diff(diff1)
    d2 = array_diff(diff2)
    ii = 0
    it = 0
    while(d1 > d2):
        l = (l/2.0)
        Inew = Ii + l*delta
        if(pred(Inew)==pred(source)):
            Inew = go_out(source,Inew,0.01)
        it = it + 1
        d1 = array_diff(Inew-Ia)
        if(it>100):
            break
    if (d1 > d2):
        print(ii)
        ii = ii + 1
        Inew = Ii
    return Inew

def iteration(itr, source, target, n, theta, j, dmin):
    targett = target
    sourcee = source
    for i in range(itr):
        print ("\n Iteration: ",i)
        adversarial_image = boundary_estimation(sourcee, targett, dmin)
        adversarial_image = go_out(sourcee,adversarial_image,0.01)
        (g, Iii2) = gradient_estimation(sourcee, targett, targett, n, theta)
        targett = efficient_update(sourcee, targett, adversarial_image, Iii2, g, j)
        if (pred(targett) == pred(source)):
            j = j/2.0
        fin = targett
        if(pred(targett)==pred(sourcee)):
            fin = go_out(sourcee,targett,0.01)
        if(array_diff(fin-sourcee)<array_diff(adversarial_image-sourcee)):
            targett = fin
            #print("uopp")

    return fin

# Note: changed 1000 -> 1
final = iteration(10,source_image,target_image,5,0.196,5.0,1.0)

pred(final)

Image.fromarray(source_image.astype('uint8')).save('/content/drive/MyDrive/Dataset/original_gtsrb3.png')
Image.fromarray(final.astype('uint8')).save('/content/drive/MyDrive/Dataset/perturbed_gtsrb3.png')
# s = measure.compare_ssim(arr[1],arr[0])

original = cv2.imread("/content/drive/MyDrive/Dataset/original_gtsrb3.png")
perturb = cv2.imread("/content/drive/MyDrive/Dataset/perturbed_gtsrb3.png")

#s = measure.compare_ssim(original,perturb,multichannel=True)
#print(s)
print(perturb)
print(original)

1/1 [==============================] - 0s 41ms/step

 Iteration:  0
1/1 [==============================] - 0s 43ms/step


<ipython-input-23-f0c48fd646c2>:12: RuntimeWarning: overflow encountered in ubyte_scalars
  d1[j][k][i] = d1[j][k][i]*d1[j][k][i]


1/1 [==============================] - 0s 20ms/step

 Iteration:  1
1/1 [==============================] - 0s 27ms/step

 Iteration:  2
1/1 [==============================] - 0s 20ms/step

 Iteration:  3
1/1 [==============================] - 0s 25ms/step

 Iteration:  4
1/1 [==============================] - 0s 31ms/step

 Iteration:  5
1/1 [==============================] - 0s 36ms/step

 Iteration:  6
1/1 [==============================] - 0s 28ms/step

 Iteration:  7
1/1 [==============================] - 0s 20ms/step

 Iteration:  8
1/1 [==============================] - 0s 24ms/step

 Iteration:  9
1/1 [==============================] - 0s 24ms/step
[[[159 159 159]
  [154 157 158]
  [157 159 159]
  ...
  [ 91  91  91]
  [ 91  91  91]
  [ 91  91  91]]

 [[159 159 159]
  [153 155 157]
  [147 153 157]
  ...
  [ 91  91  91]
  [ 91  91  91]
  [ 90  90  91]]

 [[159 159 159]
  [159 159 159]
  [156 157 158]
  ...
  [ 91  91  90]
  [ 90  90  90]
  [ 90  89  89]]

 ...

 [[ 62 131 117]
  